# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20171023_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_versions',
            field=models.ManyToManyField(related_name='document_versions', to='repository.DocumentVersion'),
        ),
    ]
