# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20171020_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=12, verbose_name='Version')),
                ('content_file', models.FileField(upload_to='uploads/%Y/%m/%d/%H/%M')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Document')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
