# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_versions',
        ),
    ]
